name: Build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: ${{ matrix.arch }} / ${{ matrix.config }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Test, Release]
        arch: [Win32, x64, ARM64]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Configure
        run: cmake -B Build -G "Visual Studio 18 2026" -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build Build --config ${{ matrix.config }} --parallel

      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          name: ffmpeg-${{ matrix.arch }}-${{ matrix.config }}
          path: |
            Build/bin/${{ matrix.config }}/*.dll
            Build/bin/${{ matrix.config }}/*.pdb
            Build/bin/${{ matrix.config }}/*.lib
          retention-days: 7
          compression-level: 9